export const threatData = [
  {
    id: 1,
    name: "Outdated SSL",
    description: "Your SSL certificates are outdated and vulnerable to interception",
    fix: "update certificate",
    severity: "high",
    points: 10,
    damage: 15,
    minLevel: 1,
    icon: "shield",
  },
  {
    id: 2,
    name: "Buffer Overflow",
    description: "Memory buffer overflow detected in application code",
    fix: "memory limit",
    severity: "critical",
    points: 15,
    damage: 25,
    minLevel: 1,
    icon: "database",
  },
  {
    id: 3,
    name: "XSS Found",
    description: "Cross-site scripting vulnerability in web form",
    fix: "sanitize input",
    severity: "high",
    points: 12,
    damage: 20,
    minLevel: 1,
    icon: "code",
  },
  {
    id: 4,
    name: "SQL Injection",
    description: "SQL injection attempt detected in database query",
    fix: "sanitize input",
    severity: "critical",
    points: 15,
    damage: 30,
    minLevel: 1,
    icon: "database",
  },
  {
    id: 5,
    name: "Weak Password",
    description: "User accounts have weak password policies",
    fix: "enforce MFA",
    severity: "medium",
    points: 8,
    damage: 10,
    minLevel: 1,
    icon: "key",
  },
  {
    id: 6,
    name: "Unpatched Software",
    description: "Critical security patches missing from system",
    fix: "apply updates",
    severity: "high",
    points: 10,
    damage: 15,
    minLevel: 1,
    icon: "package",
  },
  {
    id: 7,
    name: "Public S3 Bucket",
    description: "Cloud storage bucket is publicly accessible",
    fix: "restrict access",
    severity: "high",
    points: 12,
    damage: 20,
    minLevel: 2,
    icon: "cloud",
  },
  {
    id: 8,
    name: "Exposed Admin Account",
    description: "Admin portal is accessible without authentication",
    fix: "enforce MFA",
    severity: "critical",
    points: 15,
    damage: 25,
    minLevel: 2,
    icon: "user",
  },
  {
    id: 9,
    name: "Default Credentials",
    description: "Systems using default manufacturer credentials",
    fix: "change passwords",
    severity: "high",
    points: 12,
    damage: 20,
    minLevel: 2,
    icon: "key",
  },
  {
    id: 10,
    name: "DDoS Attack",
    description: "Distributed denial of service attack in progress",
    fix: "deploy WAF",
    severity: "critical",
    points: 18,
    damage: 30,
    minLevel: 3,
    icon: "zap",
  },
  {
    id: 11,
    name: "Insecure API",
    description: "API endpoints lack proper authentication",
    fix: "implement OAuth",
    severity: "high",
    points: 14,
    damage: 20,
    minLevel: 3,
    icon: "link",
  },
  {
    id: 12,
    name: "Data Leak",
    description: "Sensitive data being exfiltrated from network",
    fix: "encrypt traffic",
    severity: "critical",
    points: 18,
    damage: 35,
    minLevel: 3,
    icon: "database",
  },
  {
    id: 13,
    name: "Phishing Email",
    description: "Suspicious phishing campaign targeting employees",
    fix: "train users",
    severity: "medium",
    points: 10,
    damage: 15,
    minLevel: 2,
    icon: "mail",
  },
  {
    id: 14,
    name: "Malware Detected",
    description: "Malicious software detected on network endpoint",
    fix: "isolate system",
    severity: "critical",
    points: 16,
    damage: 25,
    minLevel: 2,
    icon: "bug",
  },
  {
    id: 15,
    name: "Firewall Breach",
    description: "Network firewall rules have been compromised",
    fix: "restore rules",
    severity: "high",
    points: 14,
    damage: 20,
    minLevel: 3,
    icon: "shield",
  },
  {
    id: 16,
    name: "Denial of Service (DoS)",
    description: "System is under a DoS attack causing service degradation",
    fix: "limit requests",
    severity: "critical",
    points: 16,
    damage: 28,
    minLevel: 3,
    icon: "exclamation-triangle",
  },
  {
    id: 17,
    name: "Insecure Communication",
    description: "Sensitive data transmitted over unprotected channels",
    fix: "use HTTPS",
    severity: "high",
    points: 13,
    damage: 22,
    minLevel: 1,
    icon: "paper-plane",
  },
  {
    id: 18,
    name: "Outdated Dependencies",
    description: "Outdated libraries with known vulnerabilities",
    fix: "update libraries",
    severity: "high",
    points: 11,
    damage: 18,
    minLevel: 2,
    icon: "cogs",
  },
  {
    id: 19,
    name: "Improper Session Management",
    description: "Session cookies are not securely configured",
    fix: "secure cookies",
    severity: "high",
    points: 14,
    damage: 20,
    minLevel: 2,
    icon: "key",
  },
  {
    id: 20,
    name: "Broken Access Control",
    description: "Inadequate access controls allowing unauthorized actions",
    fix: "restrict access",
    severity: "critical",
    points: 17,
    damage: 30,
    minLevel: 2,
    icon: "user-shield",
  }
  
]
